config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'candies#index'
  resources :candies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candy.rb
# Class represent candies table on database
class Candy < ApplicationRecord
  validates :name, :description, :rate, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candies_controller.rb
# Candy controller
class CandiesController < ApplicationController
  before_action :fetch_candy, only: %i[show edit update destroy]

  def index
    @candys = Candy.all
  end

  def new
    @candy = Candy.new
  end

  def create
    @candy = Candy.new(allow_candy_params)
    if @candy.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show() end

  def edit() end

  def update
    if @candy.update(allow_candy_params)
      redirect_to @candy
    else
      render :edit
    end
  end

  def destroy
    @candy.destroy
    redirect_to root_path
  end

  private

  def allow_candy_params
    params.require(:candy).permit(:name, :description, :rate)
  end

  def fetch_candy
    @candy = Candy.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candies/_form.html.erb
<%= stylesheet_link_tag 'form' %>

<%= form_with model: @candy do |form| %>
  <p>
    <%= form.label :name, 'name' %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description, 'description' %>
    <%= form.text_field :description %>
  </p>
  <p>
    <%= form.label :rate, 'rate' %>
    <%= form.number_field :rate %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/candies/edit.html.erb
<%= render 'form', candy:@candy %>

app/views/candies/index.html.erb
<h2>
  Root candy
</h2>

<nav>
  <%= link_to 'adicione um novo doce', new_candy_path %>
</nav>

<% @candys.each do |candy| %>
  <div>
    <span>
      <%= candy.name %> |
    </span>
    <span>
      <%= candy.description %> |
    </span>
    <span>
      <%= candy.rate %> |
    </span>
    <%= link_to  "Edite o doce", edit_candy_path(candy) %> |
    <%= link_to  "Apagar doce", 
      candy_path(candy),
      data: {
        'turbo-method': :delete, 
        'turbo-confirm': 'Tem certeza que deseja deletar o doce?'
      } %>
  </div>
<% end %>

app/views/candies/new.html.erb
<%= render  'form', candy:@candy %>

app/views/candies/show.html.erb
<h2>
  <%= @candy.name %>
</h2>
<p>
  <%= @candy.description %>
</p>
<p>
  <%= @candy.rate %>
</p>
<div>
  <%= link_to "edite", edit_candy_path %>
</div>

app/views/candy/new.html.erb
<%= form_with candy:@candy, data: {turbo: false} do |form| %>
  <p>
    <%= form.label :name, 'name' %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description, 'description' %>
    <%= form.text_field :description %>
  </p>
  <p>
    <%= form.label :rate, 'rate' %>
    <%= form.number_field :rate %>
  </p>
  <p>
    <%= form.submit 'Create' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CandyStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>